export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST"
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE"



export const GET_CART_SUCCESS = "GET_CART_SUCCESS"


export const REMOVE_CART_ITEM ="REMOVE_CART_ITEM"



export const SEARCH_ITEM = "SEARCH_ITEM"



export const FILTER_PRODUCT = "FILTER_PRODUCT"